/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package glogin

class App {
    String getGreeting() {
        'Hello World!'
    }

    static void main(String[] args) {
        def app=new App()
        println app.greeting
        println 'Sistema de control de usuario'.center(100)
        new MainMenu().sayMenuMain()
    }

}
